# Generated by Django 3.1 on 2020-08-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_remind', models.PositiveIntegerField(help_text='Last message ID sent to remind drink water',
                                                            null=True)),
                ('start_silence', models.TimeField(db_column='start_silence_at', null=True)),
                ('end_silence', models.TimeField(db_column='end_silence_at', null=True)),
                ('timezone', models.SmallIntegerField(help_text='Offset from UTC time, e.g: <pre>±hh</pre>',
                                                      null=True)),
                ('has_reminding', models.BooleanField(default=False, help_text='If user has active reminding')),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.DO_NOTHING,
                                               to='bot.language')),
            ],
        ),
    ]
