# Generated by Django 3.1 on 2020-09-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_silence',
            field=models.TimeField(blank=True, db_column='end_silence_at', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_remind',
            field=models.PositiveIntegerField(blank=True, help_text='Last message ID sent to remind drink water', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_silence',
            field=models.TimeField(blank=True, db_column='start_silence_at', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.SmallIntegerField(blank=True, help_text='Offset from UTC time, e.g: <pre>±hh</pre>', null=True),
        ),
    ]
