# Generated by Django 3.1 on 2020-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_blanks_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='last_remind',
            field=models.PositiveIntegerField(blank=True, help_text='Last message ID sent to remind to drink water', null=True),
        ),
    ]
